#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 gareth <gareth@GDS-Desktop>
#
# Distributed under terms of the MIT license.

"""
Project Euler
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

ss=2
x_0 = 1
x_1 = 2
x_n = 0

while x_n<4000000:
  x_n = x_0+x_1
  if x_n % 2 == 0:
    ss+=x_n
  x_0 = x_1
  x_1=x_n
print 'sum is ',ss


